# Pandas

application
* Easy handling og missing data
* size mutable
* automatic and explicit data alignment
* powerful ,flexible group by functnality
* intelligent lable-based slicing Fancy indexing and subsetting of large data set.

In [1]:
import pandas as pd

Create Dataframes

In [2]:
student={
    'id':["s2601", "s2602", "s2603", "s2604"],
    'name':["deekshith", "karthik", "jathin", "ganapthi"],
    'age':[20, 19, 21, 22]
}
df=pd.DataFrame(student)
df.shape
df.size
df.columns
df = df.rename(columns={"age":"totalage"})
df

      id       name  totalage
0  s2601  deekshith        20
1  s2602    karthik        19
2  s2603     jathin        21
3  s2604   ganapthi        22

## Export DataFrame to CSV file

In [3]:
df.to_csv("studentData.csv",index=False)

PermissionError: [Errno 13] Permission denied: 'studentData.csv'

Import CSV file

In [ ]:
#same folder
same_df=pd.read_csv("studentData.csv")
#different folder
diff_df=pd.read_csv("C:/DataScience/Pandas/subdata_pandas/employee.csv")
diff_df

,id,gender,dateofbirth,education,department,salary,starting_salary,job_time,previous_experience,minority
0,1,Male,03-02-1952,15,IT,57000,27000,8.17,NaN,No
1,2,Male,23-05-1958,16,IT,40200,18750,8.17,3.00,No
2,3,Female,26-07-1929,12,Finance,21450,12000,8.17,31.75,No
3,4,Female,15-04-1947,18,IT,21900,13200,8.17,15.83,No
4,5,Male,09-02-1955,15,Finance,45000,21000,8.17,11.50,No
...,...,...,...,...,...,...,...,...,...,...
469,470,Male,22-01-1964,12,IT,26250,15750,5.33,5.75,Yes
470,471,Male,03-08-1966,15,Engineering,26400,15750,5.33,2.67,Yes
471,472,Male,21-02-1966,15,Sales,39150,15750,5.25,3.83,No
472,473,Female,25-11-1937,12,Marketing,21450,12750,5.25,11.58,No
473,474,Female,05-11-1968,12,IT,29400,14250,5.25,0.75,No

### Import Excel file

In [ ]:
#cmd:> py -m pip install openpyxl
import pandas as pd
excel_df=pd.read_excel("subdata_pandas/expense.xlsx")
excel_df

         Date    Category       Sub-Category   Amount Payment Mode
0  2023-01-01     Grocery             Grocery      30         Cash
1  2023-01-02        Food          Restaurant     890          UPI
2  2023-01-04        Food              Zomato     257          NaN
3  2023-01-06  Essentials               Diary     120          UPI
4  2023-01-06  Essentials             Perfume    1500         Cash
5  2023-01-09     Grocery  Fruits and Veggies     456         Cash
6  2023-01-10       Bills          House Rent   16000          UPI
7  2023-01-10     Grocery      Tomato KetchUp      70          UPI
8  2023-01-12        Food                Chai      15          UPI
9  2023-01-15  Essentials      Salt and Sugar      50          NaN
10 2023-01-17     Grocery           Chocolate     100          UPI
11 2023-01-17        Food          Restaurant     780         Card
12 2023-01-18  Essentials            Food Oil     120          NaN
13 2023-01-18        Food              Zomato     230          UPI
14 2023-01-19     Grocery                Milk      26          UPI
15 2023-01-20  Essentials             Shampoo     780          UPI
16 2023-01-20  Essentials           Lunch Box     890         Cash
17 2023-01-21     Clothes               Dress    1000          NaN
18 2023-01-22     Clothes               Dress    1890          UPI
19 2023-01-23     Grocery      Bread and Milk      56         Cash
20 2023-01-24        Food  Fruits and Veggies     530         Cash
21 2023-01-26        Food                Chai      10          UPI
22 2023-01-26     Grocery               Maggi     140          UPI
23 2023-01-27        Food              Zomato     300          UPI
24 2023-01-27        Food                Chai      10          UPI
25 2023-01-28  Essentials           Bedsheets    1025         Cash
26 2023-01-29       Bills             Mobile     1650          UPI
27 2023-01-29     Grocery                Daal     150         Cash
28 2023-01-30       Bills            Cylinder    1074          UPI

Exploring Data

In [13]:
data=pd.read_csv("subdata_pandas/employee.csv")
data
data.head(10)#top 10 
data.tail(10)#bottom 10
data.shape#shape
data.size#size
data.columns#columns
data.describe()#Describe
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 474 entries, 0 to 473
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   474 non-null    int64
 1   gender               474 non-null    str
 2   dateofbirth          473 non-null    str
 3   education            474 non-null    int64
 4   department           474 non-null    str
 5   salary               474 non-null    int64
 6   starting_salary      474 non-null    int64
 7   job_time             474 non-null    float64
 8   previous_experience  449 non-null    float64
 9   minority             471 non-null    str
dtypes: float64(2), int64(4), str(4)
memory usage: 48.7 KB

In [ ]:
data.isnull().sum()

<bound method DataFrame.isnull of       id  gender dateofbirth  education   department  salary  starting_salary  \
0      1    Male  03-02-1952         15           IT   57000            27000
1      2    Male  23-05-1958         16           IT   40200            18750
2      3  Female  26-07-1929         12      Finance   21450            12000
3      4  Female  15-04-1947         18           IT   21900            13200
4      5    Male  09-02-1955         15      Finance   45000            21000
..   ...     ...         ...        ...          ...     ...              ...
469  470    Male  22-01-1964         12           IT   26250            15750
470  471    Male  03-08-1966         15  Engineering   26400            15750
471  472    Male  21-02-1966         15        Sales   39150            15750
472  473  Female  25-11-1937         12    Marketing   21450            12750
473  474  Female  05-11-1968         12           IT   29400            14250

     job_time  previous_experience minority
0        8.17                  NaN       No
1        8.17                 3.00       No
2        8.17                31.75       No
3        8.17                15.83       No
4        8.17                11.50       No
..        ...                  ...      ...
469      5.33                 5.75      Yes
470      5.33                 2.67      Yes
471      5.25                 3.83       No
472      5.25                11.58       No
473      5.25                 0.75       No

[474 rows x 10 columns]>